# syntax=docker/dockerfile:1
FROM python:3.11.1
WORKDIR /api

ARG PORT_ARG

ENV PORT ${PORT_ARG}
ENV VIRTUAL_ENV=/.venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY server.py .

CMD [ "sh", "-c", "uvicorn server:app --port $PORT" ]
